name: Update Redforce Token
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
jobs:
  update-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Decrypt and Run Scraper
        env:
          ZIP_PASS: ${{ secrets.ZIP_PASS }}
        run: |
          python decrypt.py

      - name: Commit and Push Token
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add token.txt
          git commit -m "Update Redforce Token" || exit 0
          git push
